### ISSUE TITLE
Configurable fixture file extensions?

### ISSUE THREAD

**Issue by aclemons** [willbryant/fixation#3]
The readme does not mention it, but fixation runs the fixture file through an ERB parser before loading the result as YAML. If I submit a pull request to make the extensions configurable (https://github.com/willbryant/fixation/blob/v2.2.0/lib/fixation/fixtures.rb#L18), would you be open to merging it? This would allow configuring say fixture files with the `.yml.erb` or `.yml`extension. I would not have to convince my editor that this is an ERB file and tools for linting ERBs (i.e. https://github.com/w0rp/ale) would also automatically work.

**Comment by willbryant** [comment]
IMHO `.yml.erb` is definitely better - I was surprised when I learned that Rails puts them through ERB first. I guess it is a legacy of the old days before they started using compound filenames.

Should we just add `.yml.erb` to the list for everyone?  I can't see much downside.

**Comment by aclemons** [comment]
> Should we just add .yml.erb to the list for everyone?

This also works for me! Would like a PR for this or do you just want to do it?

**Comment by willbryant** [comment]
PR would be great - thanks!
